# This is a basic workflow to help you get started with Actions

name: Node.js CD

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Deploy using ssh
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.PRIVATE_KEY }}
        port: 22
        script: |
          set -e
          cd ~/node-express-boilerplate
          GIT_SSH_COMMAND='ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/tmp/known_hosts' git pull origin master
          git status
          docker-compose -f docker-compose.yml -f docker-compose.dev.yml -f docker-compose.swarm.yml build
          docker-compose -f docker-compose.yml -f docker-compose.dev.yml -f docker-compose.swarm.yml push
          docker stack deploy -c docker-compose.yml -c docker-compose.dev.yml -c docker-compose.swarm.yml stack-name
          docker service scale stack-name_node-app=6
          docker stack ps stack-name